type="webpack"
account_id="c597c88a0e327181e7342fd3e27a5b3f"
zone_id="6ef2474eadea294303bf3a91630db7c5"
route=""
usage_model=""
compatibility_flags=[]
workers_dev=false
site={bucket="./dist", entry-point="workers-site"}
compatibility_date="2021-10-22"

[env.dev]
name="dev_stokilo_com"
route="dev.stokilo.com/*"
workers_dev=false

[env.prod]
name="prod_stokilo_com"
route="stokilo.com/*"
workers_dev=false
